-- List the number of films per category.
-- utilizar tablas film ,film category, category . A través de sus foreign keys. 

USE sakila; 

SELECT 
c.name AS categoria, 
COUNT(f.film_id) AS cantidad_peliculas
FROM category c 
INNER JOIN film_category fc
ON c.category_id=fc.category_id
INNER JOIN film f 
ON fc.film_id=f.film_id
GROUP BY c.name
ORDER BY cantidad_peliculas DESC; 


-- Retrieve the store ID, city, and country for each store.
SELECT
s.store_id, 
ci.city, 
co.country
FROM store s
JOIN address a ON s.address_id = a.address_id
JOIN city ci ON a.city_id = ci.city_id
JOIN country co ON ci.country_id = co.country_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT 
    s.store_id,
    SUM(p.amount) AS ingresos_totales
FROM payment p
INNER JOIN staff st 
ON p.staff_id = st.staff_id
INNER JOIN store s 
ON st.store_id = s.store_id
GROUP BY s.store_id;


-- Determine the average running time of films for each category.
SELECT
c.name AS categoria, 
ROUND(AVG(f.length),2) AS duracion_media
FROM film f 
INNER JOIN film_category fc 
ON f.film_id = fc.film_id
INNER JOIN category c 
ON fc.category_id= c.category_id
GROUP BY c.name;

